var GAME_LEVELS = [
  ["                     xxx    xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx   x!!!!x         ",
   "                     xxx      xxxx!!!!!!!!!!!!!!!!!!!!!!xxxx     x!!!!x         ",
   "                     xxx        xxxx!!!!!!!!!!!!!!!!!!xxxx       x!!!!x         ",
   "                     xxx          xxxx!!!!!!!!!!!!!!xxxx         x!!!!x       oo",
   "                     xxx            xxxx!!!!!!!!!!xxxx           x!!!!x       xx",
   "                     xxx              xxxvxxxxxxvxxx             x!!!!x         ",
   "                     xxx                                         x!!!!x         ",
   "                     xxx                                         x!!!!xoo       ",
   "                     xxx                                         x!!!!xxx       ",
   "                     xxx      x!!!x                              xxvvxx        o",
   "                     xxx      x!!!x               oo                          ox",
   "                     xxx   ooox!!!x               xxxx!!!!xo                 oxx",
   "               ox    xxx   xxxx!!!x                  x!!!!xxo               oxxx",
   "              oxxo   xxx      x!!!x                  x!!!!xxxo             oxxxx",
   "             oxxxo   xxx      x!!!xo        ooo      x!!!!xxxxo            xxxxx",
   "            oxxxxo   xxxoo    x!!!xxo       xxx      x!!!!xxxxxo          xxxxxx",
   "           oxxxxxo   xxxxx    x!!!xxxo               x!!!!xxxxxxxxxxxxx!!!xxxxxx",
   "@         oxxxxxxx            x!!!xxxxo             rx!!!!xxxxxxxxxxxxx!!!xxxxxx",
   "xxxxxx!!!xxxxxxxxxo           x!!!xxxxxo         oooox!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxx!!!xxxxxxxxxxo        oox!!!xxxxxxo        xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxx!!!xxxxxxxxxxxo       xxx!!!xxxxxxxo          xx!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxx!!!xxxxxxxxxxxxo        x!!!xxxxxxxxo         xx!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxx!!!xxxxxxxxxxxxxo   =   x!!!xxxxxxxxxo    =   xx!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxx!!!xxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["!!!!!!!!!!!!!!x                 x     x!!x                           xxxxxxxxxxxxxxxxxxxxxxx vvvxxxxxxvxxxxxx!x   ",
   "xxxxxvvvvxxxxxx                 x     x!!x                           x                                      x!x   ",
   "                                x    xx!!xxxxxxxxxxx                 x                                      x!x   ",
   "                   o            x    xx!!!!!!!!!!!xx                 x                                      xxx   ",
   "                  oxxx       ooox    x!!!xxxxxxx!!xx                 x                                            ",
   "                 oxxxx       xxxx    xxx!xx    xx!x                  x    o    o    o                             ",
   "                oxxxxx          x      x!x      x!x                  x    x || x || x            o                ",
   "               oxxxxxx!!xoo     x      xvx      xvx                  x                   xxx     xx    o          ",
   "             xxxxxxxxxxxxxx     x                                    x!!!!!!!!!!!!!!!!!!!!!x           xx    o    ",
   "             x                  x                                    x!!!!!!!!!!!!!!!!!!!!!x                 x    ",
   "             x                  x                                    xxxxxxxxxxxxxxxxxxxxxxx                     o",
   "          ooox                  x                                    x                                           x",
   "          xxxx     x    =    ooox     o       o                      x                                            ",
   "             x     xxxxxxxxxxxxxx    xxx     xxx     x               x                                oo          ",
   "oooo         x                  x                    x               x                      oxxxxx  xxxxx    oox  ",
   "xxxx         x                  x  o                 x               x            x      xxxxx               xxx  ",
   "             x                  x xxx       o      o x     oo        x      xo    x     ox                        ",
   "          oooxooo   =     x     x          xxx    xxxx               x     oxxxxxxxxxxxxxx                        ",
   "          xxxxxxxxxxxxxxxxx     x                         xxxx       x     xx                                     ",
   "             x                  x              o                     x                       x                    ",
   " @           x                  x      xxx    xxx               oo   xo           oo         x oooo              o",
   "xxxx         x                  x        x!!!!!!!!!!!!!!!!!!!!xxxx   xxo          xxxxxxxxxxxxxxxxxxxxxxx       ox",
   "             x       x     = ooox        xxxxxxxxxxxxx!!!!!!!!xx     xxxo =       x                            oxx",
   "!!!!!!!!!!!!!x       xxxxxxxxxxxxxxx                 x!!!!!!!!xx     xxxxxxxxxxxxxx                           oxxx",
   "!!!!!!!!!!!!!x                                       x!!!!!!!xx    oox                                       oxxxx",
   "!!!!!!!!!!!!!x                                     oxx!!!!!!xx     xxx                                      oxxxxx",
   "!!!!!!!!!!!!!x                         xo         oxx!!!!!!xx                        oo      oo            oxxxxxx",
   "!!!!!!!!!!!!!xooo       oo             xo   =    oxx!!!!!!xx                        xxxx    xxxx          oxxxxxxx",
   "!!!!!!!!!!!!!xxxxxxx   xxxx  xxxxxxxxxxxxxxxxxxxxxxx!!!!!xx  =    oo    =    x                           oxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                               xxx     ",
   "                                                                                                        x     ",
   "                                                                                                        x     ",
   "                                                    o   o                                               x     ",
   "                                               oo   x   x    oo                            oxx                ",
   "                                 |           | xx |   |    | xx                            xx                 ",
   "                     |     |     |                              |  oo |                     x  o   o   oo     ",
   "          |    |     |     |     |       oxx                       xx                       x  x | x | xx     ",
   "          o    o     o     o     o      oxx                           |             oo      x!!!!!!!!!!!x   oo",
   "          x    x     x     x     x     oxx                              oo          xxxx    x!!!!!!!!!!!x   xx",
   "     @    x    x     x     x     x    xxx                               xx          xxxxxxxxxxxxxxxxxxxxx     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx                      ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      ",
   "x                     x                                                                                   oo  ",
   "x        |   |        x                                                                                   xx  ",
   "x                     x             x                                                                 o       ",
   "x        |   |        x             x           |                                                  !!xxx      ",
   "x                     x             x           |            |     |                           o              ",
   "x        |   |        x             x           |            |     |                       !!!xxx             ",
   "x                     x             x           |            |     |                   o                      ",
   "x      o   o   o      x             x           o            o     o                 oxxx                     ",
   "x      xxxxxxxxxo     x             x           x            x     x               oxxx!!!!!!!!!!!!!!!!!!!!!!!",
   "x              xx    ox             x           x            x     x=            oxxx!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xo                   xx             x         xxxxxxxx||xxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxo                                 x         x                                    xxxxxxxxxxxxxxxxxxxxxxxx!!!",
   "xxx                                 x     oo  x                                                           x!!!",
   "                 o          xxxxxxxxxxx   xxxxx                                                           x!!!",
   "                xxo                   x   x                                                               x!!!",
   "      o         xxxo                      x                                                               x!!!",
   "     oxx        xxxx                      xx       o       o                                              x!!!",
   "     xxx              o  x                 x    | xxx   | xxx                      oo                     x!!!",
   "                      x  xo                xooo                          o         xx            o        x!!!",
   "              x!!!!!!!!!!xx     |   o   o xxxxx                         xxx                      x        x!!!",
   "              x!!!!!!!!!!x      |   x   x x                     o                         oo     x        x!!!",
   "              x!!!!!!!!!!x  oo     xxx    x!!!!!!!!!!!!!!!!!!!!!x                         xx     x       ox!!!",
   "              xxxxxxxxxxxxxxxxx!!!!xxx!!!!xxxxxxxxxxxxxxxxxxxxxxx                                x      xxx!!!",
   "xo                            xxxxvxxxvxxxx                                                    oox        x!!!",
   "xxo                                                                                            xxx        x!!!",
   "xxxo                                                                     o                       xo       x!!!",
   "xxxxoo   = = = =   oo x            o o                                  oxo                      xxo      x!!!",
   "xxxxxxxxxxxxxxxxxxxxxxx                                                oxxxo                   ooxxxo     xxxx",
   "xxx                                            oo       ooo     o     oxxxxxo                  xxxxxxo        ",
   "xxx                          xxx   xxx   xxxx|xxxx|||xxxxxxx|||xx    oxxxxxxxo                   xxxxxo       ",
   "xxx         ooo = = = = = ooox!!!!!!!!!!!!!!x!xxxx!!!xxxxxxx!!!xx   oxxxxxxxxxo                  xxxxxxo   ooo",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                          xxxxxxxxxxxxxxxxxxxx",
   "                                                                                                    |   |    x",
   "                                                                                                             x",
   "                                                                                                             x",
   "                                                                                                      |    oox",  
   "                         	                                                                      xxxxxxxxxxx",
   "                               xx  o  x                                                     ||                ",
   "        oo      oo      oo      x= o  x                                                     oo                ",
   "        xx      xx      xx      x     x                                                     xx                ",
   "    oo                          !  o  !                                                                       ",
   "    xx                                                                                                        ",
   "                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo       ",
   "                   xxx                                                ||    ||    ||    ||    ||     xx       ",
   "oo                  |            xxxxxx                                                                       ",
   "xx                               |x!!!xxxoo      o                                                          oo",
   "                                  xxxxxxxxx      x                                                          xx",
   "      o                                                   oo       xoo   o  =   o     o      o      oox       ",
   "     xxx                  o                               xx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "              o                       o                                                     |                 ",
   "             xxx         xxx         xxx                                                                      ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                    o           o           o       oo                                                        ",
   "                   xxx         xxx         xxx      xx                          o                             ",
   "                                                                 oo             x                             ",
   "                                                          oo     xx                   o                       ",
   "                                                          xx             o            x     o   o    o        ",
   "             xvx         xvx         xvx                         ||      x                  x   x    x        ",
   "                                                                                                            ||",
   "   @                                                                                                        oo",
   "  xxxx                                                                                                      xx",
   "  xoooo                                                                                                       ",
   "  xoooo                                                                         |                             ",
   "  xoooo                                                   oo     oo      o      o     o        o        o     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx     x    xxx      xxx      xxx    ",
   "        x=       oo         =      oo        =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
